<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd

In [8]:
weather_data_df = pd.read_csv("weather_data.csv")
bike_data_df = pd.read_csv("bike_trip_data.csv")
pred_df = pd.read_csv("predictions.csv",header=None)

In [4]:
weather_data_df.head()

,Date,TempHigh_F,TempAvg_F,TempLow_F,HumidityHigh_Percent,HumidityAvg_Percent,HumidityLow_Percent,VisibilityHigh_Miles,VisibilityAvg_Miles,VisibilityLow_Miles,WindHigh_MPH,WindAvg_MPH,WindGust_MPH,Precipitation_Inches,Events
0,1/1/14,69,54,39,83,68,52,10,10,8,13,4,22,0,NaN
1,1/2/14,55,44,33,83,55,26,10,10,9,21,8,31,0,NaN
2,1/3/14,58,43,28,75,49,22,10,10,10,14,4,21,0,NaN
3,1/4/14,71,57,42,89,68,47,10,10,8,16,7,28,0,NaN
4,1/5/14,59,47,34,87,59,31,10,10,4,21,10,34,0,NaN

In [5]:
bike_data_df.head()

,Date,TempHigh_F,TempAvg_F,TempLow_F,HumidityHigh_Percent,HumidityAvg_Percent,HumidityLow_Percent,VisibilityHigh_Miles,VisibilityAvg_Miles,VisibilityLow_Miles,WindHigh_MPH,WindAvg_MPH,WindGust_MPH,Precipitation_Inches,Events
0,1/1/14,69,54,39,83,68,52,10,10,8,13,4,22,0,NaN
1,1/2/14,55,44,33,83,55,26,10,10,9,21,8,31,0,NaN
2,1/3/14,58,43,28,75,49,22,10,10,10,14,4,21,0,NaN
3,1/4/14,71,57,42,89,68,47,10,10,8,16,7,28,0,NaN
4,1/5/14,59,47,34,87,59,31,10,10,4,21,10,34,0,NaN

In [10]:
pred_df.rename(columns={0:"Month", 1:"Date", 2:"Address", 3:"Prediction"})

      Month  Date                            Address  Prediction
0         1     1                   17th & Guadalupe          -1
1         1     1                     2nd & Congress          -1
2         1     1                        5th & Bowie          -1
3         1     1                     8th & Congress          -1
4         1     1           City Hall / Lavaca & 2nd          -1
...     ...   ...                                ...         ...
1235     10    31  Convention Center / 3rd & Trinity          -1
1236     10    31             Davis at Rainey Street          -1
1237     10    31                   Guadalupe & 21st          -1
1238     10    31           South Congress & Academy          -1
1239     10    31                     West & 6th St.          -1

[1240 rows x 4 columns]